[package]
name = "fp2-program"
version = "1.1.0"
edition = "2021"
publish = false

[dependencies]
sp1-zkvm = { package = "sp1-zkvm-64", path = "../../../crates/zkvm/entrypoint64" }
num-bigint = "0.4.3"
rand = "0.8.5"
