[package]
name = "sp1-gpu-logup-gkr"
description = "GPU-accelerated LogUp-GKR protocol for SP1"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[features]
tokio-blocked = ["dep:tokio-blocked", "dep:tracing-subscriber"]

[dependencies]
# sp1-gpu
sp1-gpu-cudart = { workspace = true }
sp1-gpu-utils = { workspace = true }
sp1-gpu-jagged-tracegen = { workspace = true }
sp1-gpu-zerocheck = { workspace = true }
sp1-gpu-basefold = { workspace = true }

# slop
slop-air = { workspace = true }
slop-algebra = { workspace = true }
slop-alloc = { workspace = true }
slop-commit = { workspace = true }
slop-tensor = { workspace = true }
slop-multilinear = { workspace = true }
slop-sumcheck = { workspace = true }
slop-challenger = { workspace = true }
slop-koala-bear = { workspace = true }
slop-futures = { workspace = true }
slop-basefold-prover = { workspace = true }
slop-merkle-tree = { workspace = true }
slop-bn254 = { workspace = true }
slop-symmetric = { workspace = true }
slop-dft = { workspace = true }
# sp1
sp1-hypercube = { workspace = true }

# misc
itertools = { workspace = true }
rand = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, optional = true }
tokio-blocked = { workspace = true, optional = true }
futures = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rayon = "1.10.0"

[dev-dependencies]
serial_test = "3.1"
zstd = "0.13.3"
sp1-sdk = { workspace = true}
sp1-recursion-circuit = { workspace = true }
sp1-primitives = { workspace = true }
sp1-core-executor = { workspace = true }
sp1-core-machine = { workspace = true }

[[bin]]
name = "logup_gkr_bench"
path = "bin/logup_gkr_bench.rs"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(tokio_unstable)'] }

