[package]
name = "csl-perf"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
csl-cuda = { workspace = true }
csl-machine = { workspace = true }
csl-tracing = { workspace = true }

sp1-stark = { workspace = true }
sp1-core-machine = { workspace = true }
sp1-core-executor = { workspace = true }

csv = "1.3.0"
tracing = { workspace = true }
tokio = { workspace = true }

clap = { version = "4.5.7", features = ["derive", "env"] }
bincode = "1.3.3"
prettytable = "0.10.0"

[lints]
workspace = true
