[package]
name = "csl-perf"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
csl-cuda = { workspace = true }
csl-prover = { workspace = true }
csl-tracing = { workspace = true }
csl-jagged = { workspace = true }

slop-jagged = { workspace = true }
slop-baby-bear = { workspace = true }

sp1-stark = { workspace = true }
sp1-core-machine = { workspace = true }
sp1-core-executor = { workspace = true }
sp1-prover = { workspace = true }
sp1-recursion-circuit = { workspace = true }
sp1-recursion-compiler = { workspace = true }


csv = "1.3.0"
tracing = { workspace = true }
tokio = { workspace = true }

clap = { version = "4.5.7", features = ["derive", "env"] }
bincode = "1.3.3"
prettytable = "0.10.0"

[features]
bigint-rug = [
    "sp1-core-executor/bigint-rug",
    "sp1-core-machine/bigint-rug",
    "csl-prover/bigint-rug",
]

[lints]
workspace = true
