# msrv = "1.79"

too-many-lines-threshold = 130


disallowed-types = [
    { path = "slop_koala_bear::KoalaBear", reason = "use SP1Field instead", replacement = "sp1_primitives::SP1Field", allow-invalid = true },
    { path = "slop_basefold::Poseidon2KoalaBear16BasefoldConfig", reason = "use SP1BasefoldConfig instead", replacement = "sp1_hypercube::verifier::SP1BasefoldConfig", allow-invalid = true },
    { path = "slop_koala_bear::Poseidon2KoalaBearConfig", reason = "use SP1MerkleTreeConfig instead", replacement = "sp1_hypercube::verifier::SP1MerkleTreeConfig", allow-invalid = true },
    { path = "slop_koala_bear::DiffusionMatrixKoalaBear", reason = "use SP1DiffusionMatrix instead", replacement = "sp1_primitives::SP1DiffusionMatrix", allow-invalid = true },
    { path = "slop_koala_bear::KoalaPerm", reason = "use SP1Perm instead", replacement = "sp1_primitives::SP1Perm", allow-invalid = true },
    { path = "slop_stacked::StackedPcsVerifier", reason = "use SP1Pcs instead", replacement = "sp1_hypercube::SP1Pcs", allow-invalid = true },
    { path = "slop_stacked::StackedBasefoldProof", reason = "use SP1PcsProof instead", replacement = "sp1_hypercube::SP1PcsProof", allow-invalid = true },
]

disallowed-methods = [
    { path = "slop_koala_bear::my_kb_16_perm", reason = "use poseidon2_init() or inner_perm() instead", replacement = "sp1_primitives::poseidon2_init", allow-invalid = true },
]
