[package]
name = "bn254-fp2-mul-test"
version = "1.1.1"
edition = "2021"
publish = false


[dependencies]
sp1-zkvm = { package = "sp1-zkvm-64", path = "../../../../crates/zkvm/entrypoint64" }
num-bigint = { workspace = true }
rand = "0.8.5"
