[package]
name = "sp1-recursion-circuit-old"
description = "SP1 is a performant, 100% open-source, contributor-friendly zkVM."
readme = "../../../README.md"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
keywords = { workspace = true }
categories = { workspace = true }

[dependencies]
slop-air = { workspace = true }
slop-algebra = { workspace = true }
slop-commit = { workspace = true }
slop-fri = { workspace = true }
slop-matrix = { workspace = true }
slop-symmetric = { workspace = true }
slop-challenger = { workspace = true }
slop-bn254 = { workspace = true }
slop-baby-bear = { workspace = true }
slop-uni-stark = { workspace = true }

sp1-core-machine = { workspace = true }
sp1-core-executor = { workspace = true }
sp1-stark = { workspace = true }
sp1-derive = { workspace = true }
sp1-recursion-core = { workspace = true }
sp1-recursion-compiler = { workspace = true }
sp1-primitives = { workspace = true }
sp1-recursion-gnark-ffi = { workspace = true }

itertools = { workspace = true }
serde = { workspace = true, features = ["derive"] }
rand = "0.8.5"
tracing = { workspace = true }
hashbrown = { workspace = true, features = ["serde", "inline-more"] }
num-traits = "0.2.19"
rayon = "1.10.0"

[dev-dependencies]
sp1-core-executor = { workspace = true }
sp1-recursion-core = { workspace = true, features = ["program_validation"] }
ff = { version = "0.13", features = ["derive", "derive_bits"] }
slop-challenger = { workspace = true }
slop-symmetric = { workspace = true }
slop-merkle-tree = { workspace = true }
slop-poseidon2 = { workspace = true }
zkhash = "0.2.0"
rand = "0.8.5"
test-artifacts = { workspace = true }

[features]
native-gnark = ["sp1-recursion-gnark-ffi/native"]
debug = ["sp1-core-machine/debug", "sp1-recursion-compiler/debug"]

[lints]
workspace = true
