[package]
name = "groth16-verifier-script"
version = { workspace = true }
edition = { workspace = true }
publish = false

[dependencies]
sp1-sdk = { workspace = true, default-features = true }
tokio = { workspace = true }

[build-dependencies]
sp1-build = { workspace = true }
