[package]
name = "bls12381-fp2-addsub-test"
version = "1.1.1"
edition = "2021"
publish = false


[dependencies]
sp1-zkvm = { package = "sp1-zkvm-64", path = "../../../../crates/zkvm/entrypoint64" }
num-bigint = "0.4.6"
rand = "0.8.5"
