[package]
name = "fibonacci-script"
version = { workspace = true }
edition = { workspace = true }
default-run = "fibonacci-script"
publish = false

[dependencies]
hex = "0.4.3"
sp1-sdk = { workspace = true }
tokio = { workspace = true }
sp1-prover = { workspace = true }
sp1-core-executor = { workspace = true }
sp1-build = { workspace = true, features = ["64bit"] }
sp1-core-machine = { workspace = true }
sp1-primitives = { workspace = true }

[build-dependencies]
sp1-build = { workspace = true, features = ["64bit"] }

[[bin]]
name = "plonk_bn254"
path = "bin/plonk_bn254.rs"

[[bin]]
name = "groth16_bn254"
path = "bin/groth16_bn254.rs"

[[bin]]
name = "compressed"
path = "bin/compressed.rs"

[[bin]]
name = "execute"
path = "bin/execute.rs"

[[bin]]
name = "network"
path = "bin/network.rs"

[[bin]]
name = "fibonacci-script"
path = "src/main.rs"
