[workspace]
members = [
  "common",
  "bls12381-add",
  "bls12381-decompress",
  "bls12381-double",
  "bls12381-fp",
  "bls12381-fp2-addsub",
  "bls12381-fp2-mul",
  "bls12381-mul",
  "bn254-add",
  "bn254-double",
  "bn254-fp",
  "bn254-fp2-addsub",
  "bn254-fp2-mul",
  "bn254-mul",
  "cycle-tracker",
  "ed-add",
  "ed-decompress",
  "ed25519",
  "fibonacci",
  "hint-io",
  "keccak-permute",
  "keccak256",
  "panic",
  "rand",
  "secp256k1-add",
  "secp256k1-decompress",
  "secp256k1-double",
  "secp256k1-mul",
  "secp256r1-add",
  "secp256r1-decompress",
  "secp256r1-double",
  "sha-compress",
  "sha-extend",
  "sha2",
  "ssz-withdrawals",
  "tendermint-benchmark",
  "uint256-arith",
  "uint256-mul",
  "verify-proof",
  "u256x2048-mul",
  "hello-world",
]
resolver = "2"

[workspace.dependencies]
num-bigint = "=0.4.6"
crypto-bigint = "0.5"
serde = "1.0.204"
serde_json = "1.0.132"
tiny-keccak = { version = "2.0.2", features = ["keccak"] }

[patch.crates-io]
sha2-v0-9-8 = { git = "https://github.com/sp1-patches/RustCrypto-hashes", package = "sha2", branch = "patch-v0.9.8" }
ed25519-consensus = { git = "https://github.com/sp1-patches/ed25519-consensus", branch = "patch-v2.1.0" }
sp1-lib = { path = "../../../crates/zkvm/lib" }
tiny-keccak-patched = { git = "https://github.com/sp1-patches/tiny-keccak", tag = "patch-2.0.2-sp1-6.0.0-rc.1", package = "tiny-keccak", features = [
  "keccak",
] }
