[package]
name = "sp1-gpu-jagged-tracegen"
description = "GPU trace generation for jagged/stacked polynomials"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
# sp1-gpu
sp1-gpu-cudart = { workspace = true }
sp1-gpu-tracegen = { workspace = true }

sp1-gpu-utils = { workspace = true }
sp1-gpu-basefold = { workspace = true }

# slop
slop-air = { workspace = true }
slop-algebra = { workspace = true }
slop-alloc = { workspace = true }
slop-jagged = { workspace = true }
slop-multilinear = { workspace = true }
slop-futures = { workspace = true }
slop-challenger = { workspace = true }
slop-tensor = { workspace = true }

# sp1
sp1-hypercube = { workspace = true }
sp1-core-executor = { workspace = true }
sp1-core-machine = { workspace = true }
rand = { workspace = true }
tokio = { workspace = true }
futures = "0.3"
rayon = "1.10.0"
tracing = { workspace = true }
itertools = { workspace = true }

[dev-dependencies]
test-artifacts = { workspace = true }
slop-stacked = { workspace = true }
serial_test = "3.1"
zstd = "0.13.3"
sp1-sdk = { workspace = true }
sp1-recursion-circuit = { workspace = true }
sp1-gpu-prover = { workspace = true }
sp1-recursion-compiler = { workspace = true }
sp1-gpu-zerocheck = { workspace = true }
sp1-gpu-tracing = { workspace = true }

[features]
test-utils = []

[lints]
workspace = true
