[package]
name = "csl-tracegen"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

# TODO(tqn) trim deps list
[dependencies]
csl-air = { workspace = true }
csl-cuda = { workspace = true }
csl-jagged = { workspace = true }
csl-tracing = { workspace = true }
csl-zerocheck = { workspace = true }

slop-air = { workspace = true }
slop-algebra = { workspace = true }
slop-alloc = { workspace = true }
slop-baby-bear = { workspace = true }
slop-basefold = { workspace = true }
slop-basefold-prover = { workspace = true }
slop-challenger = { workspace = true }
slop-commit = { workspace = true }
slop-futures = { workspace = true }
slop-jagged = { workspace = true }
slop-matrix = { workspace = true }
slop-merkle-tree = { workspace = true }
slop-multilinear = { workspace = true }
slop-sumcheck = { workspace = true }
slop-symmetric = { workspace = true }
slop-tensor = { workspace = true }

sp1-core-executor = { workspace = true }
sp1-core-machine = { workspace = true }
sp1-recursion-machine = { workspace = true }
sp1-primitives = { workspace = true }
sp1-stark = { workspace = true }

tracing = { workspace = true }
serde = { workspace = true }
futures = { workspace = true }
tokio = { workspace = true }
rayon = { workspace = true }

[dev-dependencies]
rand = { workspace = true }

[lints]
workspace = true
