[package]
name = "spl-basefold"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
spl-algebra = {workspace = true}
spl-multilinear= {workspace = true}
p3-challenger = {workspace = true}
p3-dft = {workspace = true}
p3-commit = {workspace = true}
p3-fri = {workspace = true}
p3-util = {workspace = true}
p3-matrix = {workspace = true}

thiserror = "1.0"
itertools = "0.12.0"
rand = "0.8.5"
serde = { version = "1.0.207", features = ["derive"] }

[dev-dependencies]
p3-baby-bear = {workspace = true}
p3-poseidon2 = {workspace = true}
p3-symmetric = {workspace = true}
p3-merkle-tree = {workspace = true}