[package]
name = "slop-basefold"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
slop-algebra = { workspace = true }
slop-multilinear = { workspace = true }
p3-challenger = { workspace = true }
p3-commit = { workspace = true }
p3-fri = { workspace = true }
p3-util = { workspace = true }
p3-matrix = { workspace = true }

thiserror = "1.0"
itertools = "0.12.0"
rand = "0.8.5"

[dev-dependencies]
slop-baby-bear = { workspace = true }
