[package]
name = "sp1-gpu-tracegen"
description = "Core GPU trace generation for SP1 machines"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
sp1-gpu-cudart = { workspace = true }

slop-air = { workspace = true }
slop-algebra = { workspace = true }
slop-alloc = { workspace = true }
slop-koala-bear = { workspace = true }
slop-futures = { workspace = true }
slop-multilinear = { workspace = true }
slop-symmetric = { workspace = true }
slop-tensor = { workspace = true }

sp1-core-machine = { workspace = true }
sp1-recursion-executor = { workspace = true }
sp1-recursion-machine = { workspace = true }
sp1-hypercube = { workspace = true }
sp1-primitives = { workspace = true }

futures = { workspace = true }
tokio = { workspace = true }
rayon = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
rand = { workspace = true }
sp1-core-executor = { workspace = true }

[lints]
workspace = true
