[package]
name = "sp1-recursion-slop"
description = "SP1 is a performant, 100% open-source, contributor-friendly zkVM."
readme = "../../../README.md"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
keywords = { workspace = true }
categories = { workspace = true }

[dependencies]
sp1-recursion-compiler = { workspace = true}
sp1-recursion-config = { workspace = true }
sp1-recursion-executor = { workspace = true, features = ["program_validation"]  }
slop-challenger = { workspace = true }
slop-sumcheck = { workspace = true }
slop-jagged = { workspace = true }
slop-merkle-tree = { workspace = true }
slop-multilinear = { workspace = true }
slop-algebra = { workspace = true }
p3-field = { workspace = true }
p3-baby-bear = { workspace = true }
tokio = { workspace = true }
zkhash = "0.2.0"
rand = "0.8"

[lints]
workspace = true