[package]
name = "csl-prover"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
csl-cuda = { workspace = true }
csl-jagged = { workspace = true }
csl-zerocheck = { workspace = true }
csl-air = { workspace = true }
csl-tracing = { workspace = true }
# csl-tracegen = { workspace = true }
csl-logup-gkr = { workspace = true }

slop-air = { workspace = true }
slop-baby-bear = { workspace = true }
slop-algebra = { workspace = true }
slop-jagged = { workspace = true }
slop-tensor = { workspace = true }
slop-basefold = { workspace = true }
slop-multilinear = { workspace = true }

sp1-stark = { workspace = true }
sp1-core-machine = { workspace = true }
sp1-core-executor = { workspace = true }
sp1-recursion-circuit = { workspace = true }
sp1-primitives = { workspace = true }
sp1-prover = { workspace = true }

tracing = { workspace = true }
sysinfo = "0.31.2"
serde = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
# for perf binary
clap = { version = "4.5.7", features = ["derive", "env"] }
bincode = "1.3.3"
rand = { workspace = true }
itertools = { workspace = true }
slop-air = { workspace = true }
slop-algebra = { workspace = true }
slop-jagged = { workspace = true }
slop-matrix = { workspace = true }
slop-sumcheck = { workspace = true }
slop-alloc = { workspace = true }

[features]
default = []
bigint-rug = ["sp1-core-executor/bigint-rug", "sp1-core-machine/bigint-rug"]

[lints]
workspace = true
