[package]
name = "rsa-script"
version = { workspace = true }
edition = { workspace = true }
publish = false

[dependencies]
rsa = "0.6"
sp1-sdk = { workspace = true, default-features = true }
tokio = { workspace = true }

[build-dependencies]
sp1-build = { path = "../../../crates/build" }
