[package]
name = "u256x2048-mul"
version = "1.0.0"
edition = "2021"
publish = false

[dependencies]
sp1-zkvm = { package = "sp1-zkvm-64", path = "../../../../crates/zkvm/entrypoint64" }
sp1-derive = { path = "../../../../crates/derive" }
num-bigint = { workspace = true }
num = { version = "0.4.1" }
rand = "0.8.5"
bytemuck = "1.15.0"
