[package]
name = "slop-bn254"
description = "BN254 scalar field with Poseidon2 for outer proving in SLOP"
readme = "README.md"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
p3-bn254-fr = {workspace = true}
slop-challenger = { workspace = true }
slop-algebra = { workspace = true }
slop-poseidon2 = { workspace = true}
slop-symmetric = { workspace = true }
serde = { workspace = true }


zkhash = "0.2.0"
ff = { version = "0.13", features = ["derive", "derive_bits"] }

