[package]
name = "csl-sys"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
slop-baby-bear = { workspace = true }

[build-dependencies]
sp1-core-executor = { workspace = true }
sp1-core-machine = { workspace = true }
sp1-recursion-executor = { workspace = true }
sp1-recursion-machine = { workspace = true }
cc = { workspace = true }
which = { workspace = true }
cbindgen = { workspace = true }
pathdiff = { workspace = true }
