[package]
name = "csl-sys"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
slop-baby-bear = { workspace = true }

[build-dependencies]
cc = "1.0"
which = "6.0"
