[package]
name = "rsa-program"
version = "1.1.0"
edition = "2021"
publish = false

[dependencies]
sp1-zkvm = { package = "sp1-zkvm-64", path = "../../../crates/zkvm/entrypoint64" }
# rsa = "0.9.6" # Check for the latest version
# rsa = { git = "https://github.com/sp1-patches/RustCrypto-RSA", tag = "patch-0.9.6-sp1-5.0.0" }
rsa = { path = "../../../../patch-64/RustCrypto-RSA-WIP" }
# rsa = { git = "https://github.com/succinctlabs/RustCrypto-RSA-WIP.git", branch = "main" }
sha2 = { version = "0.10.8", package = "sha2", features = ["oid"] } # Check for the latest version
