[package]
name = "cslpc-tracegen"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
# cuslop
csl-cuda = { workspace = true }
csl-tracegen = { workspace = true }

# prover-clean subcrates
cslpc-utils = { workspace = true }

# slop
slop-air = { workspace = true }
slop-algebra = { workspace = true }
slop-alloc = { workspace = true }
slop-multilinear = { workspace = true }
slop-futures = { workspace = true }

# sp1
sp1-hypercube = { workspace = true }
sp1-core-executor = { workspace = true }
sp1-core-machine = { workspace = true }
rand = { workspace = true }
tokio = { workspace = true }
futures = "0.3"
rayon = "1.10.0"
tracing = { workspace = true }

[dev-dependencies]
slop-stacked = { workspace = true }
serial_test = "3.1"
zstd = "0.13.3"
sp1-sdk = { workspace = true, features = ["unsound"] }
sp1-recursion-circuit = { workspace = true }
csl-prover = { workspace = true }
sp1-recursion-compiler = { workspace = true }
cslpc-zerocheck = { workspace = true }

[lints]
workspace = true
