[package]
name = "sp1-recursion-machine"
description = "SP1 is a performant, 100% open-source, contributor-friendly zkVM."
readme = "../../../README.md"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
keywords = { workspace = true }
categories = { workspace = true }

[dependencies]
sp1-derive = { workspace = true }
sp1-primitives = { workspace = true }
sp1-recursion-executor = { workspace = true, features = ["program_validation"] }
sp1-hypercube = { workspace = true }


slop-air = { workspace = true }
slop-matrix = { workspace = true }
slop-algebra = { workspace = true }
slop-koala-bear = { workspace = true }
slop-jagged = { workspace = true }
slop-maybe-rayon = { workspace = true }
slop-merkle-tree = { workspace = true }
slop-poseidon2 = { workspace = true }
slop-symmetric = { workspace = true }
slop-whir = { workspace = true }
itertools = { workspace = true }
strum = { workspace = true, features = ["derive"] }
tracing = { workspace = true }
rand = { workspace = true }
zkhash = { workspace = true }


[build-dependencies]
rand = { workspace = true }
sp1-hypercube = { workspace = true }
sp1-primitives = { workspace = true }
slop-koala-bear = { workspace = true }
sp1-recursion-executor = { workspace = true, features = ["program_validation"] }


[dev-dependencies]
sp1-core-machine = { workspace = true }
sp1-recursion-executor = { workspace = true, features = ["program_validation"] }
slop-challenger = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt", "sync"] }

[lints]
workspace = true
