[package]
name = "sp1-gpu-utils"
description = "TODO"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
# sp1-gpu
sp1-gpu-cudart = { workspace = true }
slop-algebra = { workspace = true }
slop-alloc = { workspace = true }
slop-tensor = { workspace = true }
slop-koala-bear = { workspace = true }
sp1-primitives = { workspace = true }

[dev-dependencies]
serial_test = "3.1"
zstd = "0.13.3"
sp1-sdk = { workspace = true }
sp1-recursion-circuit = { workspace = true }
sp1-gpu-prover = { workspace = true }
sp1-recursion-compiler = { workspace = true }
slop-stacked = { workspace = true }

[lints]
workspace = true
