[package]
name = "slop-koala-bear"
description = "TODO"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
p3-koala-bear = { workspace = true }
lazy_static = { workspace = true }
slop-algebra = { workspace = true }
slop-challenger = { workspace = true }
slop-poseidon2 = { workspace = true }
slop-symmetric = { workspace = true }
serde = { workspace = true }

[lints]
workspace = true
