[package]
name = "sp1-core-machine"
description = "SP1 is a performant, 100% open-source, contributor-friendly zkVM."
readme = "../../../README.md"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
keywords = { workspace = true }
categories = { workspace = true }

[dependencies]
bincode = { workspace = true }
serde = { workspace = true, features = ["derive", "rc"] }
serde_json = { workspace = true }
itertools = { workspace = true }
num = { workspace = true }
rrs-lib = { workspace = true }
slop-air = { workspace = true }
slop-koala-bear = { workspace = true }
slop-algebra = { workspace = true }
slop-whir = { workspace = true }
slop-challenger = { workspace = true }
slop-keccak-air = { workspace = true }
slop-matrix = { workspace = true }
slop-maybe-rayon = { workspace = true }
slop-uni-stark = { workspace = true }
sp1-derive = { workspace = true }
sp1-primitives = { workspace = true }
sp1-jit = { workspace = true }


slop-futures = { workspace = true }
futures = { workspace = true }

rayon = { workspace = true }
rayon-scan = { workspace = true }
sysinfo = { workspace = true }

amcl = { workspace = true, features = ["bls381"] }
cfg-if = { workspace = true }
generic-array = { workspace = true, features = ["alloc", "serde"] }
typenum = { workspace = true }

num_cpus = { workspace = true }
tempfile = { workspace = true }
tracing = { workspace = true }
tracing-forest = { workspace = true, features = ["ansi", "smallvec"] }
tracing-subscriber = { workspace = true, features = ["std", "env-filter"] }
strum = { workspace = true }
strum_macros = { workspace = true }
thiserror = { workspace = true }
hashbrown = { workspace = true, features = ["serde", "inline-more"] }

sp1-hypercube = { workspace = true }
sp1-core-executor = { workspace = true }
sp1-curves = { workspace = true }
slop-poseidon2 = { workspace = true }
tokio = { workspace = true, features = ["rt", "sync"] }
static_assertions = { workspace = true }

[dev-dependencies]
rand = { workspace = true }
num = { workspace = true, features = ["rand"] }
sp1-core-executor = { workspace = true }
test-artifacts = { workspace = true }
slop-air = { workspace = true }
slop-koala-bear = { workspace = true }
slop-algebra = { workspace = true }
slop-matrix = { workspace = true }
tiny-keccak = { workspace = true, features = ["keccak"] }
hex = { workspace = true }
elliptic-curve = { workspace = true }
k256 = { workspace = true, features = ["expose-field"] }
p256 = { workspace = true, features = ["expose-field"] }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }

[build-dependencies]
sp1-hypercube = { workspace = true }
sp1-primitives = { workspace = true }
slop-koala-bear = { workspace = true }

[features]
debug = []
bigint-rug = ["sp1-curves/bigint-rug"]

[lib]
path = "src/lib.rs"
bench = false

[lints]
workspace = true
