[package]
name = "cslpc-zerocheck"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
# cuslop
csl-cuda = { workspace = true }
csl-air = { workspace = true }
sp1-derive = { workspace = true }

# prover-clean subcrates
cslpc-utils = { workspace = true }

# slop
slop-air = { workspace = true }
slop-algebra = { workspace = true }
slop-alloc = { workspace = true }
slop-tensor = { workspace = true }
slop-matrix = { workspace = true }
slop-multilinear = { workspace = true }
slop-sumcheck = { workspace = true }
slop-challenger = { workspace = true }
slop-koala-bear = { workspace = true }

# sp1
sp1-hypercube = { workspace = true }
sp1-core-executor = { workspace = true }

# misc
itertools = { workspace = true }
rand = { workspace = true }
tokio = { workspace = true }
thiserror = "1.0"

[dev-dependencies]
serial_test = "3.1"
zstd = "0.13.3"
sp1-sdk = { workspace = true, features = ["unsound"] }
sp1-recursion-circuit = { workspace = true }
csl-prover = { workspace = true }
sp1-recursion-compiler = { workspace = true }
slop-stacked = { workspace = true }

[lints]
workspace = true
