[package]
name = "slop-futures"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
rayon = { workspace = true }
tokio = { workspace = true }
futures = { workspace = true }
thiserror = { workspace = true }

crossbeam = { workspace = true }
pin-project = { workspace = true }

[lints]
workspace = true
