[package]
name = "sp1-gpu-merkle-tree"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
# sp1-gpu
sp1-gpu-cudart = { workspace = true }
sp1-gpu-tracegen = { workspace = true }
sp1-gpu-utils = { workspace = true }

slop-algebra = { workspace = true }
slop-alloc = { workspace = true }
slop-tensor = { workspace = true }
slop-multilinear = { workspace = true }
slop-challenger = { workspace = true }
slop-koala-bear = { workspace = true }
slop-commit = { workspace = true }
slop-futures = { workspace = true }
slop-merkle-tree = { workspace = true }
slop-bn254 = { workspace = true }
slop-symmetric = { workspace = true }

# sp1
sp1-hypercube = { workspace = true }
tokio = { workspace = true }
thiserror = "1.0"

[dev-dependencies]
serial_test = "3.1"
zstd = "0.13.3"
sp1-gpu-jagged-tracegen = { workspace = true }
sp1-recursion-circuit = { workspace = true }
sp1-gpu-prover = { workspace = true }
sp1-recursion-compiler = { workspace = true }
slop-stacked = { workspace = true }

[lints]
workspace = true
