[package]
name = "sp1-zkvm"
description = "SP1 is a performant, 100% open-source, contributor-friendly zkVM."
readme = "../../../README.md"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
keywords = { workspace = true }
categories = { workspace = true }

[dependencies]
cfg-if = { workspace = true }
getrandom_v2 = { version = "0.2.15", features = ["custom"], package = "getrandom" }
getrandom_v3 = { version = "0.3.3" , package = "getrandom" }
rand = { workspace = true }
libm = { workspace = true, optional = true }
sha2 = { workspace = true }
lazy_static = { workspace = true }
embedded-alloc = { workspace = true }
critical-section = { workspace = true }

# optional
sp1-lib = { workspace = true, optional = true }
sp1-primitives = { workspace = true }
slop-koala-bear = { workspace = true, optional = true }
slop-algebra = { workspace = true, optional = true }
blake3 = { workspace = true, optional = true }

[features]
default = ["libm", "lib"]
libm = ["dep:libm"]
lib = ["dep:sp1-lib"]
bump = []
verify = ["dep:slop-koala-bear", "dep:slop-algebra", "sp1-lib/verify"]
blake3 = ["dep:blake3"]
untrusted_programs = []

[lints]
workspace = true
