[package]
name = "bls12381-mul-test"
version = "1.1.0"
edition = "2021"
publish = false

[dependencies]
sp1-zkvm = { package = "sp1-zkvm-64", path = "../../../../crates/zkvm/entrypoint64" }
sp1-lib = { path = "../../../../crates/zkvm/lib" }
sp1-derive = { path = "../../../../crates/derive" }
