[package]
name = "slop-whir"
description = "TODO"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
slop-algebra = { workspace = true }
slop-basefold = { workspace = true }
slop-multilinear = { workspace = true }
slop-challenger = { workspace = true }
slop-utils = { workspace = true }
slop-commit = { workspace = true }
slop-matrix = { workspace = true }
slop-tensor = { workspace = true }
slop-alloc = { workspace = true }
slop-baby-bear = { workspace = true }
slop-dft = { workspace = true }
slop-koala-bear = { workspace = true }
slop-stacked = { workspace = true }
slop-merkle-tree = { workspace = true }
slop-jagged = { workspace = true }

rand = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true, features = ["derive"] }
derive-where = { workspace = true }
rayon = { workspace = true }
futures = { workspace = true }
itertools = { workspace = true }

[dev-dependencies]
slop-baby-bear = { workspace = true }
slop-basefold = { workspace = true }
bincode = { workspace = true }
tracing = { workspace = true }
