[package]
name = "verify-proof"
version = "1.1.0"
edition = "2021"
publish = false

[dependencies]
sp1-zkvm = { package = "sp1-zkvm-64", path = "../../../../crates/zkvm/entrypoint64", features = ["verify"] }
hex = "0.4.3"
sha2 = "0.10.8"
