# This workflow publishes the docker image for the CLI to ghcr.io.
# Source: https://raw.githubusercontent.com/foundry-rs/foundry/master/.github/workflows/docker-publish.yml
name: Docker Publish CLI

on:
  workflow_dispatch:
    inputs:
      docker-tag:
        description: "Tag to push"
        type: string
        required: true
      dry-run:
        description: "Dry run - does not push the image"
        type: boolean
        default: false
  workflow_call:
    inputs:
      docker-tag:
        description: "Tag to push"
        type: string
        required: true
      dry-run:
        description: "Dry run - does not push the image"
        type: boolean
        default: false

jobs:
  docker-publish-cli:
    name: docker-publish-cli
    runs-on: ubuntu-latest
    # https://docs.github.com/en/actions/reference/authentication-in-a-workflow
    permissions:
      id-token: write
      packages: write
      contents: read
    timeout-minutes: 120
    steps:
      - name: Checkout repository
        id: checkout
        uses: actions/checkout@v6

      - name: Install Docker BuildX
        uses: docker/setup-buildx-action@v3
        id: buildx
        with:
          install: true

      - name: Log into registry ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set build timestamp
        id: ts
        run: echo "time=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> "$GITHUB_OUTPUT"

      # Build and push Docker image
      # https://github.com/docker/build-push-action
      # https://github.com/docker/build-push-action/blob/master/docs/advanced/cache.md
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./
          file: ./Dockerfile.build
          push: ${{ inputs.dry-run != true }}
          tags: |
            ghcr.io/succinctlabs/sp1:${{ inputs.docker-tag }}
            ghcr.io/succinctlabs/sp1:latest
          labels: |
            org.opencontainers.image.created=${{ steps.ts.outputs.time }}
            org.opencontainers.image.description=SP1 is a zero-knowledge virtual machine that proves the correct execution of programs compiled for the RISC-V architecture.
            org.opencontainers.image.licenses=Apache-2.0
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.source=https://github.com/succinctlabs/sp1
            org.opencontainers.image.title=sp1
            org.opencontainers.image.url=https://github.com/succinctlabs/sp1
            org.opencontainers.image.version=${{ inputs.docker-tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
