[package]
name = "csl-zerocheck"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
csl-cuda = { workspace = true }
csl-air = { workspace = true }

slop-tensor = { workspace = true }
slop-sumcheck = { workspace = true }
slop-algebra = { workspace = true }
slop-air = { workspace = true }
slop-alloc = { workspace = true }
slop-baby-bear = { workspace = true }
slop-multilinear = { workspace = true }

sp1-hypercube = { workspace = true }
sp1-core-machine = { workspace = true }

futures = { workspace = true }
once_cell = "1.20.3"
tracing = { workspace = true }

tokio = { workspace = true }

[dev-dependencies]
sp1-core-machine = { workspace = true }
slop-matrix = { workspace = true }
itertools = {workspace = true}

rand = { workspace = true }

[lints]
workspace = true
