[package]
name = "csl-zerocheck"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
csl-cuda = { workspace = true }
csl-air = { workspace = true }

slop-tensor = { workspace = true }
slop-algebra = { workspace = true }
slop-air = { workspace = true }
slop-alloc = { workspace = true }
slop-koala-bear = { workspace = true }
slop-multilinear = { workspace = true }

sp1-hypercube = { workspace = true }

tokio = { workspace = true }

[dev-dependencies]
slop-matrix = { workspace = true }

rand = { workspace = true }

[lints]
workspace = true
